# Generated by Django 5.1.4 on 2025-01-19 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grocery',
            name='item',
            field=models.CharField(max_length=50),
        ),
    ]
